name: Other
description: General issues, questions, or suggestions that don't fit other categories
title: "[Other]: "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reaching out! Use this template for anything that doesn't fit the other categories.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe your issue, question, or suggestion
      placeholder: What would you like to discuss?
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or information
      placeholder: Any additional details...
    validations:
      required: false
